name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Copy files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: 22
          source: "dist/*,package.json,package-lock.json"
          target: "~/cyber-store"

      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: 22
          script: |
            # NVM orqali node o‘rnatilgan bo‘lsa, uni faollashtiramiz
            if [ -s "$HOME/.nvm/nvm.sh" ]; then
              export NVM_DIR="$HOME/.nvm"
              source "$NVM_DIR/nvm.sh"
            fi

            cd ~/cyber-store

            # npm va pm2 mavjudligini tekshirish
            if ! command -v npm &> /dev/null; then
              echo "❌ npm topilmadi. VPSda to'g'ri o'rnatilmagan."
              exit 1
            fi

            if ! command -v pm2 &> /dev/null; then
              echo "⚠️ pm2 topilmadi. O'rnatilmoqda..."
              npm install -g pm2
            fi

            npm install --omit=dev
            pm2 restart cyber-store || pm2 start dist/main.js --name cyber-store
